-- AlterTable
ALTER TABLE `StockOrder` MODIFY `productDescription` VARCHAR(512) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `admin` ADD COLUMN `about` VARCHAR(512) NOT NULL DEFAULT '',
    ADD COLUMN `address` VARCHAR(512) NOT NULL DEFAULT '',
    ADD COLUMN `city` CHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN `country` CHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN `profileImg` VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN `state` CHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN `zipCode` CHAR(50) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `employee` MODIFY `shopFloorLogin` VARCHAR(50) NULL DEFAULT 'no';
